sudo: required
language: go

services:
  - docker

# Set environment variable COALA_BRANCH=<branch> to override
# the default.
env:
  global:
    - SOURCE_BRANCH=$TRAVIS_BRANCH
    - IMAGE_NAME=coala-docker:this

before_install:
  - go get github.com/grammarly/rocker

install:
  - hooks/build

script:
  - docker images
  - hooks/test

notifications:
  email: false
